addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.4.0")
addSbtPlugin("com.github.sbt" % "sbt-git" % "2.0.0")
addSbtPlugin("net.vonbuchholtz" % "sbt-dependency-check" % "4.1.0")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1032048a")
